# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Robotics Playground
email: irina.wang@tuftsceeo.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Robotics_Playground" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-datapage-generator


page_gen-dirs: true

page_gen:
- data: 'all_data'
  template: 'placemats'
  dir: all_projects
  index_files: false
  name: 'Formatted_Names'
  # # name_expr: [a Ruby expression to generate the filename (alternative to name)]
  title: 'Names'

- data: 'all_data'
  template: 'placemats'
  dir: 'spike_prime'
  index_files: false
  name: 'Formatted_Names'
  title: 'Names'
  filter_condition: "record['Formatted_Platforms'] == 'spike_prime'"

# - data: 'sudo_data'
#   template: 'placemats'
#   dir: 'Medium'
#   index_files: false
#   name: 'names'
#   title: 'names'
#   filter_condition: "record['levels'] == 'Medium'"

# - data: 'sudo_data'
#   template: 'placemats'
#   dir: 'Hard'
#   index_files: false
#   name: 'names'
#   title: 'names'
#   filter_condition: "record['levels'] == 'Hard'"
  # title_expr: [a Ruby expression to generate the filename (alternative to title)]
  # extension: [extension used to generate the filename]
  # filter: [property to filter data records by]
  # filter_condition: [a Ruby expression to filter data]
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
